var css = document.createElement("style");
css.type = "text/css";
css.innerHTML = "mark{ background:red; color:white;}";
document.body.appendChild(css);


var instance = new Mark(document.querySelector("body"));
instance.mark(['Steve Wynn','David Copperfield','Michael Douglas','Ross Levinsohn','Mario Testino','Joel Kramer','James Franco','Joel Achenbach','James Rosen','Paul Haggis','Mike Germano','Andrew Creighton','Peter Martins','Corey Lewandowski','Chuck Close','Charles Dutoit','Jack Latvala','TJ Miller','Gene Simmons','Andrea Ramsey','Jerry Richardson','Chris Matthews','Brad Kern','Andrew Duncan','Morgan Spurlock','Tavis Smiley','Eric Alexander Hewitt','Ken Friedman','Dan Johnson','Eric Davis','Donovan McNabb','Marshall Faulk','Eric Weinberger','Ike Taylor','Heath Evans','Ryan Lizza','Tom Ashbrook','Mario Batali','Cade Hudson','Jon Heely','Joe Alexander','US Appeals Court Judge Alex Kozinski','Rep Trent Franks','Bryan Singer','Harold Ford Jr','Lorin Stein','Robert Knepper','Dylan Howard','Danny Masterson','James Levine','John Hockenberry','Bruce Weber','Rep Ruben Kihuen','Rep Blake Farenthold','Shervin Pishevar','Geraldo Rivera','Johnny Iuzzini','Israel Horovitz','Garrison Keillor','Matt Lauer','Andy Rubin','David Sweeney','Nick Carter','John Lasseter','John Conyers','Charlie Rose','Ryan Seacrest','Russell Simmons','Glenn Thrush','Jameis Winston','Sylvester Stallone','Ron Jeremy','Al Franken','Adam Venit','Dallas Clayton','Mark Schwahn','Tom Sizemore','Steve Jurvetson','Richard Dreyfuss','George Takei','Andrew Kreisberg','Eddie Berganza','Steve Lebsock','Sepp Blatter','Matthew Weiner','Louis CK','Gary Goddard','Jann Wenner','Roy Moore','André Balazs','Dan Schoen','Steven Seagal','Jeffrey Tambor','Ed Westwick','Dustin Hoffman','Brett Ratner','Jeremy Piven','Michael Oreskes','Andy Dick','Kevin Spacey','Hamilton Fish','Stephen Collins','Ken Baker','Rick Najera','Mark Halperin','Knight Landesman','President George H W Bush','Leon Wieseltier', 'Roman Polanski','Ethan Kath','R Kelly','Terry Richardson','James Toback','John Besh','Lockhart Steele','Robert Scoble','Chris Savino','David Blaine','Bob Weinstein','Roy Price','Oliver Stone','Ben Affleck', 'Harvey Weinstein'], {
    "separateWordSearch": false
});
